### ISSUE TITLE
Job failed with DatabaseError: `Error converting data type varchar to numeric`

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/cohort-extractor#1015]
This [generate_cohort](https://jobs.opensafely.org/direct-oral-anticoagulant-doac-prescribing-during-covid-19/the_effects_of_covid-19_on_doac_prescribing/21839/kknghzxe73sugo2j/) job has failed with a DatabaseError: `Error converting data type varchar to numeric`

The action has run successfully before. It looks like this commit is new since the last successful run:
https://github.com/opensafely/doacs-covid19/commit/da643adc550de35817fcbefd507a0c729f176ea3

**Comment by evansd** [comment]
I think they need single quotes around the codes here:
https://github.com/opensafely/doacs-covid19/blob/da643adc550de35817fcbefd507a0c729f176ea3/analysis/study_definition.py#L87-L120

e.g. instead of:
```
"0208020X0BBAAAA": "doac_code = 13504711000001102",
```
It should be:
```
"0208020X0BBAAAA": "doac_code = '13504711000001102'",
```

**Comment by rebkwok** [comment]
Closing as this is a study code issue. @LFISHER7 is investigating.

**Comment by LFISHER7** [comment]
The suggested changes from @evansd fixed this, thanks!
