### ISSUE TITLE
Ensure patient_ids can not be matched between studies

### ISSUE THREAD

**Issue by evansd** [opensafely-core/cohort-extractor#17]
Just so we don't forget to do this!

Obviously these are hashed IDs and being output to a secure environment but they aren't strictly needed for the analysis and so we shouldn't include them. We could replace with a simple row number if it's useful to have some kind of row level identifier in there.

**Comment by sebbacon** [comment]
Just to note we are likely to still need an identifier for stuff like #136

**Comment by sebbacon** [comment]
I'm no longer clear what the advantage of rewriting ids is; the ids are non-meaningful in both backends as it is. If we want to include ids what's wrong with the backend implementation?

**Comment by evansd** [comment]
The only argument would be one of data minimisation. At present, patients extracted using one study can be crossed matched with those extracted from another study. Of course, that's in the context of all the other privacy-preserving OpenSAFELY features, so I'm not saying that's a bad thing. Just that it would be possible to avoid it if we needed to.

Happy to close.

**Comment by sebbacon** [comment]
Ah yes. Well if we add sequential numbers that is still a potentially a bit disclosive; I think we'd want to go down the hash route

**Comment by HelenCEBM** [comment]
Are we still planning to do this?

**Comment by evansd** [comment]
I think we are now planning to _not_ do this. Combining multiple extracts turns out to be useful and, now access is via the job-runner it isn't possible to combine extracts across workspaces so the privacy impact (which was negligible anyway) is mitigated.
