### ISSUE TITLE
Add hospital high cost drugs to backend

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/cohort-extractor#185]
Split out from https://github.com/opensafely/cohort-extractor/issues/163.

> Proposed [schema is here](https://docs.google.com/spreadsheets/d/1mcrsEzhzA9FMkBtPbgQGhDxxWk4xhZOx/edit#gid=1717080706)

**Comment by inglesp** [comment]
@CarolineMorton @alexwalkercebm @brianmackenna What should the API look like here?  Should it match `patients_with_these_medications`?

**Comment by brianmackenna** [comment]
So at the minute I think `patients_with_these_medications` only returns number of episodes / date of the prescription. In #163 the medicine comes from a single dataset which presumably be added in as an extra column in addition  to the primary care medicine code.

Both should be in dm+d code format from whatever system is feeding OpenSAFELY but a medicine may appeare in both the primary care and secondary care column in a given period.

 Querying the primary care record is the primary place when the medicine codelists is run through so could we add an argument like
`secondary_care = True / False / Both` (default as false) just to simply return date / number of episodes as we do presently?

**Comment by sebbacon** [comment]
We now have the data in @AnnaB45 is doing the work on understanding the schema, and particular the fact that drug names are not normalised.

**Comment by inglesp** [comment]
We'll need to add a new variable, similar to [`patients.with_these_medications`](https://docs.opensafely.org/en/latest/study-def-variables/#cohortextractor.patients.with_these_medications).

The differences with querying for existing medications are:

* We only have data to month-level granularity
* We initially only expect to know the VTM of a drug
* James will provide us some kind of mapping from the drug names in the data to VTMs -- we'll have to work out the best place to use this mapping

**Comment by brianmackenna** [comment]
Kings have sent a `.do` file with mappings over Christmas to myself and @AnnaB45 .

**Comment by CarolineMorton** [comment]
Is it best to convert this over to Python or are you happy to run it in Stata?
