### ISSUE TITLE
get ethnicity from APCS

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/cohort-extractor#270]
As discussed here https://github.com/opensafely/cohort-extractor/issues/186#issuecomment-665717565

I think as a single-purpose function for now, something like 

    patients.admitted_to_hospital_ethnicity(
      find_most_recent_nonmissing_in_period=True, # or maybe this should always happen so not an option
      return_null_if_conflict = True, # if there are at least two non-null values that don't match
      on_or_before=date,  # optional
      on_or_after=date,  # optional
      between=date,  # optional
    )

In the unlikely event that there are conflicting ethnicity values across different admissions for the same patient, then the `find_most_recent_nonmissing_in_period` and `return_null_if_conflict ` options allow us to resolve it predictably. @rohinimathur let me know if you need it to work differently. 

dictionary for ethnicity codes in APCS to follow shortly

**Comment by rohinimathur** [comment]
Agree with this approach- this matches what i've done previously in primary care data which is:
If people have multiple conflicting ethnicity codes use
a) the most frequent
b) the most recent (if all codes are equally common)

Previously when using HES data i've only received a single ethnicity code, so they must also choose the most recent or something similar.

**Comment by wjchulme** [comment]
Hadn't considered taking the most frequent non-missing. I'll add that

**Comment by rohinimathur** [comment]
![Classification of ethnicity in the CPRD](https://user-images.githubusercontent.com/63145175/90256220-50e86400-de3d-11ea-90b9-b468cdafadc4.png)

**Comment by wjchulme** [comment]
see https://github.com/opensafely/rapid-reports/blob/master/notebooks/ethnicity-codes.ipynb for ethnicity codes in APCS.

**Comment by wjchulme** [comment]
and here for (some) code labels https://www.datadictionary.nhs.uk/data_dictionary/data_field_notes/p/pds/pds_ethnic_category_code_de.asp

**Comment by rohinimathur** [comment]
@wjchulme  here is an excel lookup for APCS codes
I've just mapped the official ones on the datadictionary website, but have made a note that any code not in that list should be included under the parent category of the single 
letter code.

For example:  'A*' and  'A0' should get the same category as 'A'

[ethnicity_codelists.xlsx](https://github.com/opensafely/cohort-extractor/files/5081330/ethnicity_codelists.xlsx)

**Comment by wjchulme** [comment]
Hopefully we can correctly assign `A*`, `A0` etc with partial matching, which should also help deal with as yet unseen codes that appear in future. Either way we need a test to check for unassigned codes.

**Comment by wjchulme** [comment]
Regarding the flowchart above, our needs are slightly diffferent because we want to be able to return ethnicity from both S1 and APCS in a study definition (cf CPRD / HES) but this query is just for APCS. So the the logic will be a bit simpler:

* remove invalid codes
* remove duplicate codes entered on the same date
* take in order of preference:
   1. most frequent ethnicity code
   2. if tie for most frequent, take the most recent ethnicity code amongst the ties

**Comment by rohinimathur** [comment]
yes exactly! 
you could run the same logic for each dataset separately so we could request an ethnicity variable from each data source in the study definition and then we could decide ourselves how to combine them in the analysis stage.

**Comment by sebbacon** [comment]
I suggest:

```python
patients.admitted_to_hospital_ethnicity(
  on_conflict=["resolve"|"replace"]  # `resolve` - use heuristic to pick an ethnicity; `replace` - replace with `C` for `conflict`
  on_or_before=date,  # optional
  on_or_after=date,  # optional
  between=date,  # optional
)
```

Replacing with `C` rather than `None` allows the researcher to distinguish between nulls and conflicts, which might be useful.

----------

Is there a separate case for a `anywhere_ethnicity()` function that encodes our suggested heuristic as best-practice, as well?  I can imagine that being useful to a lot of people who just want ethnicity...

**Comment by rohinimathur** [comment]
Yes I agree that having an option for anywhere_ethnicity is really useful.
In that scenario you'd probably want to limit to 'known' ethnicity (ie/ exclude codes which indicate unknown, not-stated) so that they are not prioritised over other ethnicity codes which indicate a valid ethnicity grouping.

**Comment by HelenCEBM** [comment]
Just checked 16-category ethnicities in APCS, ie. the first character only in a quick SQL query and found approximately:
- 9k people with more than 2 different ethnicities
- 200k with exactly 2 different ones
- 10m with exactly 1
(we have 5 years or so of APCS, and these numbers include those who have died/deregistered since their APCS record, as well as those for whom we already have ethnicity from GP records)

Given this I don't think it's worth building in "most frequent" and instead keep it simpler by just taking "latest" (this would match our process for GP records too, I think?) - unless it takes no more time to do "most frequent or latest".

**Comment by brianmackenna** [comment]
I agree - I think latest one. For other studies we return `number_of_episodes`. Would it be possible to return `number_of_unique_episodes` so its available in descriptives and for informing individual studies? 

As discussed previously though there is a separate but related work that should be done on ethnicity and understanding why people have more than one ethnicities recorded (this is expected as ethnicity can be fluid and also affected by who fillls the form in, what is offered as possible answers etc.). All this would help us understand a little more about disprorportiante efefct of covid on certain groups.

**Comment by HelenCEBM** [comment]
Liam just mentioned that the default value can sometimes be "white" so if people have mixed records, the best option could be take the latest non-white one. He said there was some evidence for this issue - @rohinimathur have you come across it? However, this bias could equally also apply to the people with only one recorded ethnicity in SUS and we have no way of correcting it in those cases (which represent the vast majority).

**Comment by rohinimathur** [comment]
It's not something I've looked into specifically. I think the recording of a default ethnicity probably depends on the software. I know for hes APCS completeness is really high compared to GP records, but we found that a lot of the difference was just made up of unknown codes so it's possible the recording of white as default may also be more common in that setting. 

I agree that going with latest ethnicity is sensible given low numbers of conflicts. One thing to consider (if not too onerous) is that if people have more than one ethnicity and the latest is unknown, to use the latest valid ethnicity.

**Comment by HelenCEBM** [comment]
> One thing to consider (if not too onerous) is that if people have more than one ethnicity and the latest is unknown, to use the latest valid ethnicity.

I think this is straightforward as we can (hopefully) always exclude any values that don't provide any information i.e. blanks, "99", and those starting with "Z" (any others I missed?)

**Comment by HelenCEBM** [comment]
The conflict we possibly haven't dealt with is where the patient has two different codes recorded on the same date (and this date was their most recent non-null record) - this should be vanishingly unlikely but could happen - maybe in this case we take the latest alphabetically to avoid the white-default issue.

**Comment by rohinimathur** [comment]
agree, it will be a small issue but good to have a  method in place to approach it!

**Comment by rohinimathur** [comment]
> > One thing to consider (if not too onerous) is that if people have more than one ethnicity and the latest is unknown, to use the latest valid ethnicity.
> 
> I think this is straightforward as we can (hopefully) always exclude any values that don't provide any information i.e. blanks, "99", and those starting with "Z" (any others I missed?)

I think there is a code for 'refused' as well.

**Comment by HelenCEBM** [comment]
Some further observations. 

For the ~200k with more than one different ethnicity in APCS:
- around a third have White ethnicities only (Brit, Irish and/or other),  around a third have at least one code for White ethnicity, and the remaining third do not have any White codes. 
  - If we were to assume that the sometimes-white people are probably not white (e.g. white was the default option), then it's possible that overall two thirds of this group are non-white. 
- around a quarter have the same number of different ethnicities as the total number of (non-missing) ethnicity records (i.e. looking for most frequent would have two or more equally ranked options)

There is an outstanding question on what to do with the other data sources (Outpatient and A&E). I'm not sure how much more work it will add to get these too, and whether they can be combined in the backend (ie. to get latest/most common ethnicity across all three _before_ this is fed into the study def). For context on how useful this could be:
- OP has a similar pattern to inpatients with 9-10m different people's ethnicities and a similar very small number of people with multiple different ones. 
- Combining the ~10m patients with ethnicity recorded in outpatients with the ~10m in inpatients gives a total around 13.5m different patients with at least one ethnicity recorded. 
- A&E is messier, with more conflicts as may be expected (though patients with consistent-ethnicity remain the overwhelming majority, and again there are around 9-10m of them).

**Comment by HelenCEBM** [comment]
Final pragmatic proposal after discussion with @inglesp @ghickman :

New function as follows:
```
patients.ethnicity_from_sus(
    setting = "inpatients" (or "outpatients" or "emergency") 
    on_conflict = "most frequent" (or, later could add option to "drop")
)
```

- We don't think that date limits would be required but please shout if any objections

The function will find the most frequent (or latest where equal) ethnicity in each individual dataset: 
- `APCS`, column=`Ethnic_group`
- `OPCS`, column=`Ethnic_group` (requires checking, doesn't appear in tpp-schema notebook as of Oct 31st - but it's either this or `Ethnic_Category`!)
- `EC`, column=`Ethnic_Category`
 
These can be combined in the study definition to fill any ethnicities not known from GP records, with suggested priority order IP > OP > A&E. 

Mapping / reference values: 
- ethnicity codes found in APCS and EC are listed [here](https://github.com/opensafely/rapid-reports/blob/master/notebooks/ethnicity-codes.ipynb). 
  - The `CPNS` table gives a convenient lookup table, which are hopefully the same as [this](https://datadictionary.nhs.uk/data_elements/pds_ethnic_category_code.html) reference document and [Rohini's lookup table](https://github.com/opensafely-core/cohort-extractor/issues/270#issuecomment-674574255). 
  - We should take the first digit to map to our usual 16 categories, and **ignore** instances of `None`/null values, `99`, and `Z` (not stated) such that the function only returns informative values (or consistent blank where unkown). 
  - We will ideally also map these to the broader 6 categories - there are different ways of grouping them so we want to be consistent with our previous methods (built into our method for taking ethnicity from GP records). This could be done in the study def if problematic in backend.

**Comment by ghickman** [comment]
@HelenCEBM @inglesp – What did we think the `setting = "inpatients" (or "outpatients" or "emergency")` kwarg was going to do?  It looks like it would configure which table would be use, or maybe prioritised?  But I think we probably want to use all tables all the time?

**Comment by HelenCEBM** [comment]
@ghickman yes, we would probably always want to use all 3, but we were thinking they'd need to be brought into the study definition separately (and then prioritised) because that would be quicker to build in the back end than building a function that looks across all three....

**Comment by ghickman** [comment]
@HelenCEBM – aha!  I've not used the same method as the GP eth lookup, so I don't think we're going to see the same slowdown.  I'll leave `setting` out for now and we can revisit if we see performance issues.
