### ISSUE TITLE
Convert aftershocks work to measures-framework

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/cohort-extractor#343]
Related to #169

Helen's [deciles work](https://github.com/opensafely/aftershocks-notebook/blob/master/lib/functions.py) uses lots of custom SQL. We want to integrate this into OpenSAFELY backends and/or pipeline actions.

**Comment by HelenCEBM** [comment]
Update: Most of the extraction has been rewritten and is successfully using the usual cohortextractor for the next phase of analysis, and @CarolineMorton is working on pipeline actions.

**Comment by HelenCEBM** [comment]
I think we can close this now
