### ISSUE TITLE
Support measures in EMIS backend

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/cohort-extractor#352]

**Comment by evansd** [comment]
I _think_ this will already work. The measures framework just runs a vanilla study definition repeatedly, calling the `set_index_date` method each time with a new date. This method just reevaluates all the date expressions in the study with the new index date and initialises a new backend with the updated definitions. (The date expression evaluation stuff all happens before the backend is initialised so it's not something backends need to know about.)

After the cohorts are extracted the backend plays no further role in the measures framework.

**Comment by inglesp** [comment]
Oh wow, that'd be nice!

Will close this once we've validated it works.

**Comment by HelenCEBM** [comment]
Suggest closing this and reopen if it turns out to be a problem
