### ISSUE TITLE
Add SGSS SGTF/channels data

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/cohort-extractor#436]
When available, will be needed ASAP for a range of studies.
cc @rozeggo

**Comment by rozeggo** [comment]
Paired with #437 for updating.

**Comment by rozeggo** [comment]
From Chris_TPP:
New variant SGSS is in OpenSAFELY . @Jonny has just built it. One more column called SGTF, just on the positive tests table. Not on the all tests table. Column is varchar for safety but has values blank, 0, 1, and 9.
