### ISSUE TITLE
Support ignoring null numeric_values

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/cohort-extractor#458]
To implement the PRIMIS vaccine spec I need to find the date of the latest observation with a non-null value.

I propose updating the API to allow:

```
patients.with_these_clinical_events(
    codelist,
    returning="last_date_in_period",
    ignore_null_values=True,
    ...
)
```

`ignore_null_values` would be valid for any value of `returning`, and would add `AND NumericValue IS NOT NULL` to the relevant SQL in `_patients_with_events`.

**Comment by evansd** [comment]
NumericValue is non-nullable, sadly. So the best we could do is to ignore zero values.

**Comment by inglesp** [comment]
Fiddlesticks

**Comment by evansd** [comment]
At least, it _was_. Might be worth double checking in the current live version.

**Comment by inglesp** [comment]
OK, what about:

```
patients.with_these_clinical_events(
    ...
    numeric_value_in_range=(lower, upper),
    ...
)
```

where the endpoints are inclusive, and `lower`/`upper` being `None` means no lower/upper bound.

That would allow researchers to filter out obviously nonsense values for eg BMI.

**Comment by evansd** [comment]
Sounds like a good solution
