### ISSUE TITLE
Support typed binary file format

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/cohort-extractor#503]
Per discussions #434 and https://github.com/opensafely-core/roadmap/discussions/7#discussioncomment-504176, we should support a typed binary file format, because we already infer column types in cohortextractor and this information is thrown away when we output as a CSV. Keeping this information will vastly improve memory usage and performance.

I propose a new `--output-format` flag, thus:

    cohortextractor:latest generate_cohort --study-definition study_definition --output-format dta

I think the supported formats should be `feather`, `stata`, and CSV: `feather` because it's basically the best format, `stata` because `feather` is not support by stata.  CSV can be the default to maintain backwards compatibility.

This is a very simple change: it just needs `feather` adding to the R docker image and a few lines changing in `cohortextractor` (`pandas` already supports reading and writing in `feather` format).

The only question is if we should support R's `rds` format as well, it's a few more lines of code an a [new dependency](https://github.com/ofajardo/pyreadr) which smells like it might be less reliable than feather; I defer to @wjchulme's opinion on this.

**Comment by inglesp** [comment]
> CSV can be the default to maintain backwards compatibility

Can we have a deprecation period?

**Comment by sebbacon** [comment]
>> CSV can be the default to maintain backwards compatibility
>
> Can we have a deprecation period?

I thought this too. I think the problem is we don't have a good versioning story pinned down yet (everyone's just using `cohortextractor:latest`).

**Comment by wjchulme** [comment]
> The only question is if we should support R's `rds` format as well

I would say don't bother. If we have `feather` support, then that should be the accepted way to move data.frames around and import them into R. And this should be documented as the "official" way.

It'll still be useful to use `rds` files for other R objects (possibly including data.frames with additional attributes that `feather` can't support), but only for passing objects _between_ R scripts.
