### ISSUE TITLE
`DBPROCESS is dead or not enabled` error

### ISSUE THREAD

**Issue by evansd** [opensafely-core/cohort-extractor#514]
Occasionally our database queries in the TPP backend die with:
```
_tds.DatabaseError: DBPROCESS is dead or not enabled
```

Apparently this indicates that the connection has died or been closed for some reason. We already have [retry logic][retry] in place but this only reruns the query with the same connection object and doesn't attempt to reconnect so it won't solve this particular problem.

Probably the simplest solution is just to make it reconnect, but we need to make sure we only do this if we've previously written results to the temporary database. If we're relying on temporary tables, these are only scoped to the session and therefore if we reconnect they won't be there anymore.

[retry]: https://github.com/opensafely-core/cohort-extractor/blob/62dd5c1c8750d2586dac2e15a14e9099c5a7ed89/cohortextractor/mssql_utils.py#L128

This has only happened 5 times before, but mysteriously 4 of those times have been with one particular job of Krishnan's which suggests that there's something non-random about when this failure occurs.

```console
$ cd /e/high_privacy/logs
$ find . -name 'logs.txt' | xargs grep DBPROCESS
./2020-12/job-non-specific-immunity-research-generate-cohort-d2x2nppfqwtdijup/logs.txt:2020-12-14T19:26:18.946660100Z _tds.DatabaseError: DBPROCESS is dead or not enabled
./2021-03/job-post-admission-admissions-research-generate-2019pool02-io67zaxfxrq2xult/logs.txt:2021-03-26T08:16:30.671976500Z _tds.DatabaseError: DBPROCESS is dead or not enabled
./2021-03/job-post-admission-admissions-research-generate-2019pool10-4bhrvxuo5yiukdi6/logs.txt:2021-03-30T11:50:26.390697300Z _tds.DatabaseError: DBPROCESS is dead or not enabled
./2021-03/job-post-admission-admissions-research-generate-pool03-ahccqrmes77fuoqz/logs.txt:2021-03-17T01:56:06.909225600Z _tds.DatabaseError: DBPROCESS is dead or not enabled
./2021-03/job-post-admission-admissions-research-generate-pool07-tvqompymgjl66hsc/logs.txt:2021-03-17T01:52:45.325538300Z _tds.DatabaseError: DBPROCESS is dead or not enabled
```

**Comment by sebbacon** [comment]
Related to https://github.com/opensafely-core/job-runner/issues/184 which might be a quicker "fix" depending on other priorities / feels

**Comment by evansd** [comment]
Going to close this optimistically until we hear that it's still an issue.
