### ISSUE TITLE
Chaotic encoding of categorical variables in `.dta` output format

### ISSUE THREAD

**Issue by alexwalkercebm** [opensafely-core/cohort-extractor#534]
In contrast with dates (as described in #533) categorical columns that are created by e.g. `patients.categorised_as` _are_ preserved in the `.dta` output format. However, because of the slightly odd way that Stata encodes categorical variables, this can lead to some unpredictable behaviour.

Categorical variables in Stata are encoded as an `int`, with a label associated with each value. Unless manually specified, when a variable is [encoded](https://www.stata.com/manuals/dencode.pdf), values are assigned a zero indexed integer in alphabetical order. For example the categories `0-44, 45-69, 70+` would be encoded as `0, 1, 2`. This appears to be the behaviour that occurs when using `df.to_stata()` here.https://github.com/opensafely-core/cohort-extractor/blob/a5ec79afc4c01b1541197a04e0852c4268349f35/cohortextractor/pandas_utils.py#L11

This would work fine sometimes, but could cause unpredictable encoding. For example, if there were no people in the `0-44` category, then `45-69, 70+` categories would be assigned `0, 1` instead of `1, 2`.

Worse than this is categories that are returned as numbers, for example: the way that ethnicity has been defined in most cases so far, e.g. [here](https://github.com/opensafely/long-covid/blob/19609d7caaaf9303ea191b5492171597dde9d077/analysis/common_variables.py#L89-L98). This returns a categorical variable with the numbers 1-5, which `df.to_stata()` dutifully encodes as `0, 1, 2, 3, 4` and labels as `1, 2, 3, 4, 5`.
______
I'm not sure what the solution is here, as I don't think `df.to_stata()` has a way of specifying how categorical variables are encoded.

The solution that would at least restore sanity would be to change categorical variables to strings/ints as appropriate and then let people categorise in the downstream Stata. Obviously we then lose the memory/speed advantage.

**Comment by alexwalkercebm** [comment]
To further illustrate:
![image](https://user-images.githubusercontent.com/24895935/115584852-05872f00-a2c3-11eb-9d9a-fd80dc67b895.png)

**Comment by sebbacon** [comment]
Sorry for being a bit slow, but why does this matter? The labels are still right?

**Comment by alexwalkercebm** [comment]
In Stata the labels are really only for presentation. The values that you can interact with are the underlying encoded values.

In the illustrated example above if you did `drop if ethnicity == 1` then it would drop the 149 people in ethnicity category `3`, because it's encoded as `1`.

**Comment by alexwalkercebm** [comment]
The underlying reason for this is that most of Stata's stats libraries can _only_ deal with numeric values. Encoding a variable using [encode](https://www.stata.com/manuals/dencode.pdf) is really just a workaround for this, rather than being a well thought through categorical data type, but it seems that `df.to_stata()` treats it as the latter.

**Comment by evansd** [comment]
> In the illustrated example above if you did drop if ethnicity == 1 then it would drop the 149 people in ethnicity category 3, because it's encoded as 1.

The problem here seems to be hardcoding opaque, and arbitrary, internal ID numbers into a script. I don't know what the correct stata is for this, but presumably there's some way of saying "give me the int that corresponds to label X"? Otherwise you're just begging for subtle bugs if categories get added or rearranged. Plus your script becomes incomprehensible to anyone who doesn't happen to know the internal IDs that happen to be used for the specific datafile the script was run against.

So I'm inclined to say that the unpredicatable IDs are a fuzz-test against bad coding practice, and thus a feature :)

**Comment by sebbacon** [comment]
> presumably there's some way of saying "give me the int that corresponds to label X"

hahahaha

**Comment by alexwalkercebm** [comment]
> > presumably there's some way of saying "give me the int that corresponds to label X"
> 
> hahahaha

You'd think so wouldn't you. I'm not aware of any method of doing that apart from `decode` which turns the variable into a string with the label value, but the previously mentioned limitations with stats libraries mean that the variables you feed into them have to be numeric.

@krishnanbhaskaran could you confirm that I'm not missing anything when it comes to variable labels in Stata? The TLDR is that `cohortextractor` can now output `.dta` files, but the way it exports categorical variables is essentially the same as doing `encode my_variable`, and I think this is problematic.

**Comment by krishnanbhaskaran** [comment]
I don't think you're missing anything. "encode" (which it seems that to_stata is using) will do what Alex described above. I don't think it's at all reliable for what you have in mind, as stated, it will assign different labels if some categories are not present in the data. It should possible to display the contents of the label that "encode" has created (label list <variablename> should do this) but I don't think they're actually returned into accessible variables.

I would therefore lean towards leaving non-numeric variables as strings and allowing the labelling to be done in Stata.
(The "proper" way one would label things up in Stata is to define the label explicitly, and then apply the defined label to the variable, e.g.
label define ethnicitylab 1 "white" 2 "asian" 3 "black"
label values ethnicity ethnicitylab 
)

Hope helps!

**Comment by evansd** [comment]
OK, thanks @krishnanbhaskaran and @alexwalkercebm that's really helpful (if disappointing!). In that case I think probably our best bet is to leave categoricals as strings as suggested but try to push forward [this issue](https://github.com/opensafely-core/stata-docker/issues/1) on adding `gzsave` support so we can use `.dta.gz` files to reduce space requirements.

**Comment by alexwalkercebm** [comment]
I agree that leaving as strings and doing it explicitly in Stata seems like the only good solution.

There's still other benefits in exporting as `.dta`:
- Stata will read that format much quicker than a CSV
-  if the date issue in #533 is sorted:
   - some file size savings
   - simpler Stata code, because the date conversion will already be done.

**Comment by krishnanbhaskaran** [comment]
Agree with those advantages.

Just to check though - I'm not entirely clear why to_stata would be encoding something like ethnicity which comes out of the study def as numbers only. How does it know it is categorical and not quantitative? If it were just treated as numeric and exported directly without going through an "encode" type procedure, then there would be no problem - it could be stored as a numeric data type to help with space but would have no (confusing) label attached. The numeric variable could then be explicitly labelled in Stata as above.

**Comment by evansd** [comment]
Ethnicity is actually encoded as a string here (they're categories assigned to codelists and categories are always strings in the system). But, confusingly, this has been papered over by using CSV which can't distinguish numeric-looking strings from integers.

**Comment by alexwalkercebm** [comment]
I think in the case of ethnicity, it's because it's defined with `returning="category"`, so cohortextractor infers that it is categorical. The returned values are only numeric because that's what's recorded in the codelist. They could also be strings.

It also does the same with any variable defined using `patients.categorised_as`.

**Comment by krishnanbhaskaran** [comment]
I see. 

Incidentally, even if ethnicity goes into stata as a string, providing to_stata chooses the shortest length possible (str1) it would take up no more memory than a "byte" numeric variable. Basically str1 takes up 1 byte; str2 2 bytes and so on. So up to str8 they are not necessarily any worse than numeric types for space.
