### ISSUE TITLE
New variable for healthcare worker flag recorded at vaccination time

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/cohort-extractor#544]
Data on whether or not a person is a healthcare worker, collected at the time of COVID-19 vaccination, will be available in OpenSAFELY-TPP soon. This info will be really useful for classifying patients by JVCI priority groups (amongst vaccinated only) and therefore for comparative vaccine effectiveness studies. 

This is just a placeholder until more details about the variable in the database are available.

**Comment by wjchulme** [comment]
This dataset is now in OpenSAFELY-TPP. From Jonny:

> There is a new `HealthCareWorker` table with two columns - `PatientId` and `HealthCareWorker` (values are all `'Y'`).
There were duplicates in the file that we received so I've only selected distinct rows.
591,484 distinct rows in total.

**Comment by wjchulme** [comment]
Need to do some QC to check that everyone in `HealthCareWorker` table has a corresponding vaccination date in praimry care data

**Comment by wjchulme** [comment]
There might be some

suggested variable signature:
There's no event date, so the variable signature is about as simple as it gets:

```
patients.vaccinated_health_care_workers(
   returning = "binary_flag",
   return_expectations={}
)
```

strictly speaking the returning argument isn't necessary, but useful to make it explicit I think

**Comment by evansd** [comment]
From reading the related Slack threads the meaning of this flag appears to be: "was a healthcare worker at time of covid vaccination". So I don't think supplying a reference date would be the right thing to do here. 

I wonder if the duplicates records are from the second dose?

**Comment by wjchulme** [comment]
Reference date might be useful to highlight that this was a one-off extract of vaccinated healthcare workers on date X, and so any healthcare workers who were vaccinated after date X will be missed. There will be some but not many -- eg due to pregnancy, illness, etc. 

Similar to how the household variable (currently) only accepts one reference date.

Unfortunately we don't know what X is.

**Comment by evansd** [comment]
Given it looks like we're not going to get the actual date the extract was taken, I'd be tempted to go with something like this:
```py
patients.with_health_care_worker_flag_on_covid_vaccine_record(
   data_extract_name="spring_2021_extract_1"
   returning = "binary_flag",
   return_expectations={}
)
```
That is, give the extract a name which is specific enough for us to identify it in future if we get subsequent extracts, but sufficiently vague that no one will mistake it for an exact date.

I've also made the variable name a bit more verbose and specific, as is my wont :)

Thoughts?

**Comment by sebbacon** [comment]
What's the source of the data? Should that be incorporated into the function call somehow?

**Comment by wjchulme** [comment]
From Ben

> This data is from the NHS England COVID-19 data store, and reflects information collected at the point of vaccination where recipients are asked by vaccination staff whether they are in the category of health and care worker

**Comment by wjchulme** [comment]
looks like this will in fact not be a one-off extract. The dataset will be updated routinely (weekly or monthly, though still not sure). At this point it's not likely that there will be many changes, since most H&SC workers have already been fully vaccinated. 

There are no person-level dates attached to the flag, i.e., when the person was vaccinated / when the person was flagged as a H&SC worker. So we can only infer the flag was created _no later than_ the date the dataset was ingested by TPP. I think also that the dataset get's overwritten in the database each time it is updated. So there is currently no way to tell who has been added since the previous update. Even if we could choose the specific extract, it would get messy to keep track of these using `data_extract_name="spring_2021_extract_1"`.

How about removing the `data_extract_name` argument, and adding a `returning = "date"` option which returns the date the dataset was updated in OpenSAFELY-TPP. (Or better, the ingestion date into TPP. Or even better, the extraction date from the NHS data store. The last two aren't already present in the database, though.) At least then users know that any vaccinations occurring after this date (minus X days) will not have an up-to-date H&SC worker flag.

**Comment by wjchulme** [comment]
Get the latest build date for that dataset using 

```sql
select max(BuildDate) from BuildInfo where BuildDesc ="HealthCareWorker"
```

**Comment by wjchulme** [comment]
On reflection, we could also just let users derive this from the latest dates notebook https://github.com/opensafely/database-notebooks/blob/master/notebooks/database-builds.ipynb as you'd do for getting cut-off dates for deaths, admissions, etc

**Comment by evansd** [comment]
@wjchulme Yeah, I think our best move is just to remove the `data_extract_name` argument and leave it to users to worry about cut-offs in the same way as for other datasets
