### ISSUE TITLE
Return "number_of_matches_in_period" for SGSS tests

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/cohort-extractor#563]
The number of PCR or LFT tests taken indirectly tells us about a person's health seeking behaviour / exposure / occupation / etc. This will be useful for the comparative vaccine effectiveness analysis to check balance between matched pfizer and az recipients.

**Comment by CarolineMorton** [comment]
I think this is increasingly going to be of interest in studies in the near future. One thing that occurs to me is, is the data available to us to query?

**Comment by wjchulme** [comment]
We have the `AllTests` SGSS tables `https://reports.opensafely.org/reports/opensafely-tpp-database-schema/` which in theory contains every test, positive and negative, reported via SGSS. But the consistency of data flows across different pillars, PCR/LFTs, etc is not a sure thing, so it would have to be used with care.

**Comment by sebbacon** [comment]
@wjchulme, what does "used with care" mean in practice? Clear documentation? Or something we can assert in code?

If the former, it would probably be useful for the implementor to have the suggested documentation up-front; in any case, it'll need writing at some point, and I'm prioritising this to be picked up in the next 4 weeks, so if you can sketch it out, that'd be useful. Thanks!

**Comment by wjchulme** [comment]
There are a lot of unknowns with the values that are returned by `patients.with_test_result_in_sgss`. In particular test provenance and test coverage. So by "used with care" I just mean that the value returned by counting the number of tests in a given period my be difficult to interpret or misleading without more information. Basically, it makes it less useful.

A note in the documentation will help to make these caveats clear.

What will help even more is being able to _filter_ tests by LFT/PCR and pillar / lab type, so that test provenance can be better understood and the coverage of testing data over time can be more easily gauged. Pillar/lab type is requested in #248. Currently, the only way to get LFT/PCR info is [by `returning` (not filtering) the `case_category` of the first-ever positive test](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.with_test_result_in_sgss--case-category-type-of-test-used), but there's also the `LFT_flag` variable in the `SGSS_AllTests_Positive` and `SGSS_AllTests_Negative` tables which should have this information for all tests.

**Comment by acagreen17** [comment]
Having the number of PCR or LFT tests would also be really useful for the descriptive breakthrough COVID stuff - it could help to explain some of the differences in rates that we are seeing (i.e., higher rates in groups such as health care workers/immunocompromised might be due to higher rates of testing).

**Comment by sebbacon** [comment]
Just to note Ben G has said this is a big research priority.
