### ISSUE TITLE
Add `Symptomatic` column as a return option for SGSS

### ISSUE THREAD

**Issue by alexwalkercebm** [opensafely-core/cohort-extractor#581]
The `AllTests` versions of the SGSS tables contain a `Symptomatic` column, which [3 different users](https://ebmdatalab.slack.com/archives/C010SJ89SA3/p1623410097410800) have identified as being important for their studies.

It's not clear from the [schema](https://github.com/opensafely/database-notebooks/blob/master/notebooks/database-schema.ipynb) what exactly this contains, but it's quite likely that the raw column would be acceptable to return.

**Comment by evansd** [comment]
In the `AllTests_Positive` dataset the possible values are: "N", "U", "Y".
In the `AllTests_Negative` dataset the possible values are:  NULL, "false", "true".

Because we don't support NULLs for boolean variables we can't represent this as a boolean without losing information. So we could either export the raw string, or normalise to something like "", "Y", "N".

Either way, this shouldn't be a big job.

**Comment by alexwalkercebm** [comment]
If we were to normalise, it would be useful to still be able to distinguish between `positive_and_symptomatic` and `negative_and_symptomatic` etc. Though I guess that could be done with two different variables.

Otherwise, normalising sounds good to me if it's easy.

**Comment by rozeggo** [comment]
agree with alex that we would need to know symptomatic status for positives and negatives. Thanks!

**Comment by evansd** [comment]
Yes, absolutely. It's just about whether we bundle that up with the symptomatic status (e.g `PS` for positive symptomatic and `NS` for negative symptomatic) or require it to be extracted as a separate column. I can see pros and cons either way.

**Comment by alexwalkercebm** [comment]
I think either way of doing it would be okay, so long as it's clearly documented. Perhaps whichever is easiest to implement?

**Comment by CarolineMorton** [comment]
This is a priority I think. I can see there is some work on this already. @StevenMaude let me know if you need me to do anything?

**Comment by StevenMaude** [comment]
@CarolineMorton: I'm fixing #616 first — that issue blocks merging other pull requests here as the tests currently fail. I spotted it while working on #612 today. I'll then return to #612 to check it over, and then request a review from you after that, if that's OK?

It would be helpful if you, or another researcher if you've no time, to test this column extraction with a simple study following a merge of #612.
