### ISSUE TITLE
Household Variable Debugging 

### ISSUE THREAD

**Issue by annaschultze** [opensafely-core/cohort-extractor#628]
There are several inconsistencies in the household variable that is currently blocking work on a number of projects which utilises this. Briefly: 

- People in the same household have different household level characteristics (such as care home status, IMD, and rural/urban designation), even when these are extracted on the same date. This affects a non-trivial number of households. 
- We are unable to replicate the TPP calculated household_size when manually calculating household size (counting individuals in the same hhid), with almost 10% of households having a different hhsize. 

A separate issue is that the median size of care home households is low (~2). This may be caused by some individuals 'missing' because they're part of different EHR systems, and it may simple be the case that we need to exclude small households when doing care home analyses on the household level. Would be good to have confirmation that we think this is truly the case however..! 

The code for the checks we've done so far are here: https://github.com/opensafely/households-short-data-report and the issues are summarised and quantified in more detailed here: https://docs.google.com/document/d/1zHiJULgnrbOUTXU67Lw45Yv22hC5e6Knx5FQWlBgMPc/edit 

Johnny from TPP has looked at that google doc and commented suggesting these are issues on either the cohort extractor or our end, but we're not able to pinpoint these. Once an engineer is assigned it might be useful to have a call to discuss these.

**Comment by annaschultze** [comment]
@sebbacon tagging as I don't think I have permission to assign people.

**Comment by sebbacon** [comment]
Thanks @annaschultze; it would also be useful context to understand which current projects this is critical for, and their timescales..?

**Comment by annaschultze** [comment]
The household variable is currently used in: 

Ongoing projects: 
- Children and covid infection risk (snots) update [urgent, for cabinet office] 
- Household classifier analyses [urgent, for cabinet office] 
- Care home spatial hazards [not urgent, but unless resolved in next 3.5 weeks project will have to be cancelled as there'll be no resource to complete] 

Published 
- Ethnicity analyses (in Lancet); households played a big part in this [not critical but important given high profile of work] 
- Care homes short data report [not urgent but we should include information when it comes back from review] 

Having spoken to Roz we feel this is very high priority given the first two projects alone; happy to provide more details (can't seem to tag Roz in this workspace however...)

**Comment by sebbacon** [comment]
Thanks. @BeckyLumbard and I will prioritise - will aim for someone to pick this up next week

**Comment by sebbacon** [comment]
Suggested work plan for whoever picks this up:

* Read supporting code and documentation in the ticket
* Set up call with @annaschultze and an experienced researcher from DL team (e.g. Will, Alex, Helen) to fill out gaps in understanding
* Write up a plan of investigation here
* Review it with Seb
* Do it!

**Comment by rebkwok** [comment]
I've taken a look at the code in https://github.com/opensafely/households-short-data-report, the relevant cohort-extractor code, and the database itself.  I think I have some reasons for at least some of the discrepancies, but it will be useful to talk through the details of the checks.

1) The patient population selected
households-short-data-report uses 
```
population=patients.registered_with_one_practice_between(
        "2020-01-01", "2020-02-01"
    ),
```

This selects patients registered at a single practice between these dates.
`patients.registered_as_of("2020-02-01")` would select patients registered on 2020-02-01, which selects 231, 560 more patients.

2) The very large upper end of the range of total household size appears to be due to the way the total size is calculated - when I queried the database for maximum household size with minimum TPP percentage, Ifound an entry where household size is 2135, and TPP Percentage is 1%, which would give a total size of 213,500.

3) Consistency of household characteristics
I haven't been able to dig into the database for this one yet, but, as described in the summary doc, household characteristics (MSOA, IMD, rural/urban classification, carehome type) are retrieved from the PatientAddress table.  The patient address table can have multiple entries for each patient, and they're not always consecutive, so there may be multiple entries that cover the date of interest (in this case, 2020-02-01).  The cohortextractor determines which is the most likely latest entry that matches the date of interest and returns that.  This could mean that patients with the same household ID are returned data from different addresses, and therefore different address characteristics.

**Comment by annaschultze** [comment]
Hi @rebkwok, thank you so much for doing this! 

1. Good spot, sorry for missing that..! I re-ran this and the agreement is much better, there's only around 0.05% discrepant households, as opposed to >10%. I assume that disagreement might be due to the way that the cohortextractor chooses which address to extract if multiple are registered on the same date? 
2. Agree with this, and I think this can be caveated with the (known) limitations when we calculate % TPP coverage 
3. I think I follow this but just so confirm: people can be registered with multiple addresses, on the same date? Or is it the case that there are sometimes missing date entries for the registered address? If there are multiple addresses and the cohortextractor chooses a different one compared to what TPP have used to define the household that explain why people can be in the same household, but some are in a care home and some are not, and some are in different MSOAs. 


If [3] is confirmed I think it'd be useful to perhaps have an estimate of how often this happens (if that's easy to get?), or we can just use our estimates of inconsistencies, and agree on what a sensible way forward would be - i.e, should those households be disregarded as they may or may not be an actual household. That might be a wider discussion though.

**Comment by rebkwok** [comment]
So for #3, I haven't explicitly looked at the data yet, but the cohort-extractor's code comments state:
```
        # Note that current addresses are recorded with an EndDate of
        # 9999-12-31. Where address periods overlap we use the one with the
        # most recent start date. If there are several with the same start date
        # we use the longest one (i.e. with the latest end date). We then
        # prefer addresses which are not marked "NPC" for "No Postcode" and
        # finally we use the address ID as a tie-breaker.
``` 
Yes, an address entry has a start date and an end date, and a patient can have multiple entries, which sometimes overlap, so there can be multiple addresses with start/end dates that cover the same date.  When that happens, we order the overlapping dates to select the one with the most recent start date; then the one with the latest end date, then addresses with postcodes - I can't remember the reason, but sometimes there are duplicate entries where one has a postcode and one doesn't, and we assume the one with the postcode is most accurate.

I'll try to run a query on the DB to see how many patients registered on 01-Feb-2020 have multiple entries.  The Household table does also have an MSOA entry, so there may be a possibility to select the address entry that matches the household entry for that table on the MSOA value.  We would only want to do that for an `address_as_of` with a reference date of 01-Feb-2020 though, and we'd want to discuss further whether that's a good idea or not.

**Comment by rebkwok** [comment]
So it looks like the following numbers of patients have multiple values on 01-Feb-2020:
- MSOA: 3,409,318 patients
- RuralUrbanClassification - 1,681,561 patients
- IMD - 3,475,116 patients

Not all of these would result in discrepant address values for patients in different households, but they culd. 

MSOA is also found on the practice, and it seems it may be more common to use practice MSOA than patient address MSOA? https://github.com/opensafely/SRO-PULSE-OXIMETRY-UPD/blob/bd1aab45cedaf824427404040c355cc35487c01c/analysis/common_variables.py#L62-L81

**Comment by rebkwok** [comment]
@annaschultze Are there still follow up tasks related to this, or can we close this issue?

**Comment by annaschultze** [comment]
Hi @rebkwok - the original debugging was for Emily's project which is now paused, so the only one working on this now is Kevin Wing (who I don't think is a member of opensafely-core, so I cannot tag him). If you're able to just post a notice to the main Slack channel notifying him that you're closing the issue, but that this is where he can find the required info for the SDR, that'd be great. Thank you!
