### ISSUE TITLE
Filtering number of matches in SGSS by test type

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely-core/cohort-extractor#646]
I am splitting this issue from #563 

The aim is the return **the number of tests** in a **time period** filtered **by lab type**. The API would look like:

```python
number_of_all_pcr_tests=patients.with_test_result_in_sgss(
            pathogen="SARS-CoV-2",
            test_result="any",
            restrict_to_earliest_specimen_date=False,
            test_type="PCR",
            returning="number_of_matches_in_period",
        )

```

**Comment by sebbacon** [comment]
Can you communicate this to the wider opensafely team, and specifically people invested in it? (I think Will, maybe Millie, BenG)? Thanks!
