### ISSUE TITLE
Identify the breaking version of the presto/trino client

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/cohort-extractor#665]
Carry out: 

> a very tedious bisection process where we identify either the oldest version of prestodb which breaks, or the newest version of trino that works. Then hopefully looking at the diff will help us work out where the failure is.
>
> Fortunately the broken version fails immediately on just a SELECT 123; query, so we can check quite quickly whether it exhibits the problem or not.

([link](https://github.com/opensafely-core/cohort-extractor/pull/663#issuecomment-936325248))

When we've worked out the breaking version, probably submit a bug report to trino; or discover if it's already fixed; set up some way to monitor when the bug is fixed; when it is, revert https://github.com/opensafely-core/cohort-extractor/pull/663 and upgrade the trino client.

**Comment by rebkwok** [comment]
@evansd if I understand it correctly, this only breaks on prod, not locally.  I was thinking to run a cohortextractor container on EMIS to try to identify the breaking version, but then I realised that I can't install anything.  Did you have an idea of how best to do this?  I guess I could build a version of the image, push it and pull it down on EMIS to test it?

**Comment by rebkwok** [comment]
The breaking version of `trino` is 0.305; all `presto-python-client` versions work fine.

v0.305 contains just one main commit, which renames presto to trino.

Changing the headers from `X-Trino...` back to `X-Presto...` here, as suggested by @evansd, makes it work, implying that we're not actually running against Trino after all.
https://github.com/trinodb/trino-python-client/commit/bfd10796fa0cfd3217438b67d6b77e4b601f2175#diff-63c4401777e4635610fc86748f7ec8408c27badb58d5969c417b21bd98b02357

**Comment by iaindillingham** [comment]
I'm going to close this issue and move it to _Done_, as (as far as I can tell) there's no more work to do.
