### ISSUE TITLE
Requirement to add `=1` to properly evaluate boolean variables in study definition

### ISSUE THREAD

**Issue by LisaHopcroft** [opensafely-core/cohort-extractor#684]
@LFISHER7 and I had a strange issue recently in our [PINCER](https://github.com/opensafely/pincer-measures) study definition, when dealing with EGFR values.

We were extracting the EGFR value and comparator as follows:

```
egfr=patients.with_these_clinical_events(
        codelist=egfr_codelist,
        find_last_match_in_period=True,
        returning="numeric_value",
        on_or_before="index_date - 3 months",
        return_expectations={
            "float": {"distribution": "normal", "mean": 45.0, "stddev": 20},
            "incidence": 0.5,
        },
    ),

egfr_comparator=patients.comparator_from(
        "egfr",
        return_expectations={
            "rate": "universal",
            "category": {
                "ratios": {  # ~, =, >= , > , < , <=
                    None: 0.10,
                    "~": 0.05,
                    "=": 0.65,
                    ">=": 0.05,
                    ">": 0.05,
                    "<": 0.05,
                    "<=": 0.05,
                }
            },
            "incidence": 0.80,
        },
    ),
```

And then creating the variable `egfr_between_1_and_45` identifying valid EGFR values between 1 and 45:

```
egfr_between_1_and_45=patients.categorised_as(
        {
            "0": "DEFAULT",
            "1": """ (egfr>=1) AND (egfr < 45) AND ( NOT egfr_comparator = '>' ) AND ( NOT egfr_comparator = '>=' ) AND ( NOT egfr_comparator = '~' ) AND ( NOT ( egfr = 1  AND egfr_comparator='<') ) """,
        },
        return_expectations={
            "rate": "universal",
            "category": {
                "ratios": {
                    "0": 0.94,
                    "1": 0.06,
                }
            },
        },
    ),
```

We were then using `egfr_between_1_and_45` in our indicator denominator definition as follows:

```
indicator_k_denominator=patients.satisfying(
        """
        egfr_between_1_and_45
        """,
    ),
```

However, we realised that `indicator_k_denominator` was TRUE for all patients, irrespective of the value of `egfr_between_1_and_45` (i.e., `egfr_between_1_and_45` was correct, but the definition of `indicator_k_denominator` was not working as required). I think I'm right in saying that we worked this out by running [this job](https://jobs.opensafely.org/datalab/pincer/pincer-measures/4305/ijtowhtdg455hots/), which used [this commit](https://github.com/opensafely/pincer-measures/tree/b16d60a561621ccc732ba164d440cbb07f9f945b) of the PINCER repo.

We were able to fix this by amending `indicator_k_denominator` to test for `egfr_between_1_and_45=1` as follows:

```
indicator_k_denominator=patients.satisfying(
        """
        egfr_between_1_and_45=1
        """,
    ),
```

This change is encapsulated by [this commit](https://github.com/opensafely/pincer-measures/commit/f0487dcca891694839c2fac8bea2f6ec0c09ed5c#diff-407d70c1c5419308c20fe3cd10547b89b90b113f5aa64fa754474c9cd268a932).

This seems strange, because the other indicator numerators/denominators are working without having to add the `=1`. However, this is the only indicator definition that is based on numeric data *and* a pretty complicated series of conditions relating to that numeric data and its comparator.

Note that this *didn't* happen with dummy data, it only happened when the jobs ran on the server.

Is there something we're missing about why the `=1` is required in the case of `indicator_k_denominator` but not in other cases?

**Comment by evansd** [comment]
Ah yes, I can see how this might be pretty confusing. The problem is the quotes around the numbers here which means the keys are strings, rather than integers:
```
{
    "0": "DEFAULT",
    "1": """ (egfr>=1) AND (egfr < 45) AND ( NOT egfr_comparator = '>' ) AND ( NOT egfr_comparator = '>=' ) AND ( NOT egfr_comparator = '~' ) AND ( NOT ( egfr = 1  AND egfr_comparator='<') ) """,
},
```
This means you're creating a categorical with two categories which happen to be called `0` and `1' but as far as the system is concerned they may as well be `a` and `b` -- it doesn't treat the values as having any meaning.

If you remove the quotes then the keys become integers:
```
{
    0: "DEFAULT",
    1: """ (egfr>=1) AND (egfr < 45) AND ( NOT egfr_comparator = '>' ) AND ( NOT egfr_comparator = '>=' ) AND ( NOT egfr_comparator = '~' ) AND ( NOT ( egfr = 1  AND egfr_comparator='<') ) """,
},
```
And the fact that there are just the values 0 and 1 mean that they'll be treated like booleans and will behave as you originally expected.

**Comment by LisaHopcroft** [comment]
Thank you for the clear explanation @evansd
