### ISSUE TITLE
Duplicated rows in/large numbers are being suppressed from the measures table

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/cohort-extractor#685]
The [measures][1] framework allows a researcher to suppress small numbers (`0 < x <= 5`) by passing `small_number_suppression=True`. @acagreen17 and @robinyjpark have encountered two issues with the measures framework, which they feel may be related:

* Duplicated rows in the measures table
* Large numbers are being suppressed from the measures table

## Duplicated rows in the measures table

A _measures table_ is a table generated by calling `cohortextractor generate_measures` on a cohort.

Robin has written a study (which study?) with four actions:

* A `cohortextractor generate_cohort` action that extracts non-ethnicity variables for a population
* A `cohortextractor generate_cohort` action that extracts an ethnicity variable for the same population
* A scripted action that joins the outputs of the previous two actions
* A `cohortextractor generate_measures` action that generates a measures table from the output of the previous action

Apparently, this pattern is common; extracting all variables (non-ethnicity plus ethnicity) is discouraged (why?).

Robin used this pattern to generate a measures table from a big cohort and a small cohort. Initially, the scripted action operated on both the big cohort and the small cohort; the generated measures table contained duplicate rows. She then modified the scripted action to operate on either the big cohort or the small cohort; the generated measures table did not contain duplicate rows. Was the `cohortextractor generate_measures` action ingesting both the big cohort and the small cohort?

## Large numbers are being suppressed from the measures table

In [this Slack 🧵][4], Millie and Robin describe an issue with small number suppression. Their hypothesis is that small numbers are being suppressed _before_ aggregation; small numbers should, in fact, be suppressed _after_ aggregation.

For example, given the following measure:

```python
measures = [
    Measure(
        id = "antipsychotic_groups_any",
        numerator = "antipsychotic_any_incidence",
        denominator = "population",
        group_by = ["dementia", "care_home", "learning_disability", "autism", "serious_mental_illness"],
    ),
]
```

We would expect the following measures table, which here contains [dummy data][2]:

<img width="653" alt="Screenshot 2021-11-22 at 14 44 07" src="https://user-images.githubusercontent.com/477263/143574699-2d5241c5-a05e-44a3-a63e-e120a1fea1cc.png">

I wondered whether this was a misunderstanding: I wondered whether  Millie and Robin thought this measures table should _then_ be grouped by unique values of `dementia`/`date`, `care_home`/`date` etc., the numerators and denominators summed, the values calculated, and small numbers suppressed. This isn't the case. To calculate numerators, denominators, and values for `dementia`/`date`, `care_home`/`date`, etc. would require separate instances of `Measure`. For example:

```python
measures = [
    Measure(
        id = "antipsychotic_groups_any",
        numerator = "antipsychotic_any_incidence",
        denominator = "population",
        group_by = ["dementia"],
    ),
    Measure(
        id = "antipsychotic_groups_any",
        numerator = "antipsychotic_any_incidence",
        denominator = "population",
        group_by = ["care_home"],
    ),
    # etc.
]
```

Robin tells me that there is not misunderstanding 🙂. Large numbers are being suppressed from the measures table for fine-granularity groups, such as those groups produced by the variables `dementia`, `care_home`, `learning_disability`, `autism`, and `serious_mental_illness` taking the value of either `True` or `False`. However, she's unable to separate this issue from the previous issue: fixing the previous issue also fixed this issue.

## Next steps

* Could you link to the study where there are duplicated rows in the measures table, @robinyjpark?
* As an aside, could you also link to other studies that use the non-ethnicity/ethnicity workaround?
* @acagreen17 attached a file to the Slack 🧵 that, when passed to `cohortextractor generate_measures`, would exhibit large numbers being suppressed. @iaindillingham will investigate

[1]: https://docs.opensafely.org/measures/
[2]: https://docs.opensafely.org/study-def-expectations/
[3]: https://docs.opensafely.org/actions-scripts/
[4]: https://ebmdatalab.slack.com/archives/C33TWNQ1J/p1637590072221900

**Comment by robinyjpark** [comment]
Thanks, Iain! This is a very clear description of the issue. This is the relevant study: https://github.com/opensafely/HbA1c-levels

**Comment by acagreen17** [comment]
From my understanding, ethnicity (and sometimes IMD, plus other potentially "static" variables) are extracted separately when running studies over multiple time points as it saves time. @alexwalkerepi and @LFISHER7 probably know more about this than me. Examples of repo's where this happens include:

-  https://github.com/opensafely/antipsychotics-prescribing-during-COVID-19  
- https://github.com/opensafely/pincer-measures
- https://github.com/opensafely/mechanical-valve-anticoag

**Comment by iaindillingham** [comment]
Thanks @robinyjpark and @acagreen17 👍🏻 

@acagreen17, you shared an input file in the Slack 🧵 called *input_2019-01-01.feather*. Which study did this file come from? Which instance of `Measure` resulted in large numbers being suppressed from the measures table?

**Comment by iaindillingham** [comment]
See also:

* #626
* opensafely/documentation#488

**Comment by acagreen17** [comment]
@iaindillingham the _input_2019-01-01.feather_ came from [this](https://github.com/opensafely/antipsychotics-prescribing-during-COVID-19) study. It's dummy data though, so only available locally, unless you run it yourself to generate dummy data. 

I've thought about this issue a bit more and I don't think that large numbers being suppressed from the measures table, rather multiple rows of small numbers (due to multiple categories when using `group-by`). I think the issue is the **layout** of the measures. Probably worth a call to discuss.

**Comment by iaindillingham** [comment]
I revisited these potential bugs in early December, but unfortunately couldn't recreate them. I remember discussing the suppression potential bug with @benbc, but we couldn't determine how it might have been occurring. I think the duplicated rows potential bug might have been an artefact of the study, rather than the measures framework itself.

I propose closing this issue with this comment. If either of these potential bugs re-emerge, then we can create separate issues for them, linking back to this issue for context.
