### ISSUE TITLE
Using fixed and dynamic dates with patients.maximum_of()

### ISSUE THREAD

**Issue by venexia** [opensafely-core/cohort-extractor#695]
Our study defines the start of follow-up for each individual as the latest of study start date (a fixed date) and 2 weeks after second vaccination (a dynamic date that differs for each individual). We therefore wanted to derive a date variable that reflected this and could then be used to define the exposures, outcomes and covariates for the study. 

I tried using `patients.maximum_of()` but it doesn't like the combination of a fixed and dynamic dates.  Assuming this is an issue and I haven't missed something, I think potential solutions are to add functionality that would define a variable equal to index_date for everyone that could then be fed to `patients.maximum_of()` or to update `patients.maximum_of()` to allow combinations of a fixed and dynamic dates.

**Comment by evansd** [comment]
Ah yeah, this is an annoying limitation of the `maximum_of()` function at the moment. The long term solution to this is the new "Databuilder" project we're working on which has a much more consistent design and doesn't suffer from these weird and apparently arbitrary limitations in the same way. But that's a way off being ready for real world use at the moment.

In the meantime, there's a nasty workaround I've just thought of where you define a function like this:
```py
def make_fixed_date(date_str):
   # Abuse `categorised_as` to give us a value which is fixed for every patient where "1=1" i.e. all of them
    return patients.categorised_as({date_str: "1=1", "1900-01-01": "DEFAULT"})
```

And then you can write:
```py
study = StudyDefinition(
    ...
    fixed_date = make_fixed_date("2021-10-18"),
    ...
    max_date = patients.maximum_of("fixed_date", "some_other_date_column"),
)
```

That's not a thing of beauty but it might be enough to unblock you for now.

**Comment by evansd** [comment]
Just looking at this again and realised there's a very slightly neater way of writing this if you don't want `fixed_date` to appear in your output:
```py
study = StudyDefinition(
    ...
    max_date = patients.maximum_of(
        "some_other_date_column",
        fixed_date=make_fixed_date("2021-10-18"),
    ),
)
```

**Comment by venexia** [comment]
Thank you for your responses - I tried something similar before Christmas and couldn't get it to work but am going to try again!

**Comment by alexwalkerepi** [comment]
Venexia tells me the suggested solution didn't work. Am I right in thinking that the variable that `make_fixed_date` would return would be a categorical rather than a date? Would that be an issue for `patients.maximum_of`?

**Comment by evansd** [comment]
Ah yeah, Millie tried this and it didn't work. The problem isn't quite what you suggested though Alex. It does actually work fine on the real data, but it breaks the dummy data generation. It ends up triggering an error like:
```
AttributeError: Can only use .dt accessor with datetimelike values
```
(Slack thread [here](https://ebmdatalab.slack.com/archives/C33TWNQ1J/p1642164422086900?thread_ts=1641990382.049800&cid=C33TWNQ1J))

As mentioned in the thread, I don't think there's a neat workaround here — it just needs fixing properly in the cohortextractor. Possibly someone's available to pick this up now. I'll raise it in the channel.
