### ISSUE TITLE
ONS-Mortality - addition of place of death field 

### ISSUE THREAD

**Issue by amirmehrkar** [opensafely-core/cohort-extractor#696]
Existing Dataset: ONS-Mortality

Amend to add: EXTRA field "place of data"  - Amir to obtain from ONS Schema

OpenSAFELY TPP only - Amir to inform

Timescale: ideally to expose Jan 2022 onwards 

Development needs: cohort extractor to be able to query. 

Purpose: approved Nuffield/ONS project: https://docs.google.com/document/d/118JpJGhioz3lJ_K4ZcYHG9FNvonrcir7yfEvqjXnb9M/edit#heading=h.ya05m3g3094i 

@brianmackenna to be aware for when we allocate co-pilot

**Comment by amirmehrkar** [comment]
The ONS-mortality dataset is being updated for TPP from 10th January 2022.

It will include a new field: Place of death.

The list of items will be categorised as: 

- Home
- Care Home
- Hospice
- Hospital
- Other Communal Establishments
- Elsewhere

TPP has received a sample extract to test.

@brianmackenna @sebbacon this will need cohort extractor work to query.

**Comment by brianmackenna** [comment]
Are we getting `place of death` for all previous deaths or only new ones?

**Comment by amirmehrkar** [comment]
Should be all previous - that is what the Data Sharing Agreement implies and I have re-clarified today with ONS. See email forward.

**Comment by rebkwok** [comment]
@amirmehrkar This issue says that ONS-Mortality is an existing dataset.   It's not in the TPP database; is it actually ONS_Deaths, or is that something different?  Are we waiting on TPP adding it still?  (Apologies for my ignorance :slightly_smiling_face:)

**Comment by HelenCEBM** [comment]
@rebkwok looks like this will replace the existing ONS deaths dataset (with same name) but include an extra column. However, TPP don't have this yet 
![image](https://user-images.githubusercontent.com/24392156/150550061-293a9668-195d-4cd7-ab79-df1a4f44adfa.png)
