### ISSUE TITLE
Renal Registry

### ISSUE THREAD

**Issue by BeckyLumbard** [opensafely-core/cohort-extractor#706]
Data ingest form here: https://docs.google.com/spreadsheets/d/1u7CzMRnmoFvDafPRbCPnBj6NRR3nNAMLeOJ6L2-JksE/edit#gid=0

**Comment by amirmehrkar** [comment]
Attached schema
[UKRR_OS_schema_2022_02_17.xlsx](https://github.com/opensafely-core/cohort-extractor/files/8088920/UKRR_OS_schema_2022_02_17.xlsx)

**Comment by amirmehrkar** [comment]
TPP and UKRR have been in touch; still waiting for Data Sharing Agreement to be signed.

**Comment by amirmehrkar** [comment]
Signed - i need to contact UKRR to finalise - but TPP and UKRR have been in touch.

**Comment by amirmehrkar** [comment]
Amir contacted TPP; UKRR; and @LFISHER7 to proceed with data transfer and Louis to have discussion with developers to update  cohort extractor.

**Comment by amirmehrkar** [comment]
@andrewscolm @LFISHER7 need to add analysis restriction to this please

**Comment by LFISHER7** [comment]
The UKRR data is now available within OpenSAFELY-TPP. [This doc](https://docs.google.com/document/d/1jqQZiZHhJptUyCK_k-YrQ3lOSmBY1B_j6RsaHFFg89E/edit#heading=h.jk9o38u30gcx) summarises the dataset and proposes a single new variable to capture all the data needed.
