### ISSUE TITLE
Antibody and antiviral deployment

### ISSUE THREAD

**Issue by BeckyLumbard** [opensafely-core/cohort-extractor#713]

**Comment by amirmehrkar** [comment]
Data Ingest Form for this dataset here https://docs.google.com/spreadsheets/d/1JxtK_ZXl9zRowuBKA8fEeIQaY6Zvcqzho2RIMXmzAPI/edit#gid=0

Tracker cell here: https://docs.google.com/spreadsheets/d/1eHwqPHSm5d9Lebg7SQNJmAXiiEjjzp1lMFM7ymZE7YI/edit#gid=1970852217&range=A4

We are awaiting the data schema still.

**Comment by brianmackenna** [comment]
The data schema has been shared. 


https://docs.google.com/document/d/1jfkCjrHDacYo1NB3ZtPiSbXMNK6tD6Qf07E7s2urB2I/edit

**Comment by rebkwok** [comment]
@HelenCEBM's [notes](https://docs.google.com/document/d/1gAuqY778h97abB4kI8pazbahGAnk8S3dlwwBvXrn-GI/edit?usp=sharing)

**Comment by HelenCEBM** [comment]
Suggested study def query [draft]

```
covid_therapeutics = patients.with_covid_therapeutics(
	returning = "date",
	approved= True,
	with_these_therapeutics = therapeutic_codelist,
	with_these_indications = indication_codelist,
	on_or_after = "index_date",
	date_format="YYYY-MM-DD"
)
```

- `returning` options: "date", "therapeutic", "risk group", "region"
- `approved`: True = 'Approved' or 'Treatment Complete',
     False = 'Treatment Not Started' or 'Treatment Stopped' ??
- `therapeutic_codelist`: current options 'Casirivimab and imdevimab', 'Molnupiravir', 'Remdesivir', 'sarilumab', 'Sotrovimab' , 'Tocilizumab' [may contain trailing spaces but assume will be stripped in backend]
- `indication_codelist` = one or more of 'non-hospitalised','hospital_onset', 'hospitalised_with'
- DATES: taken from earliest of `TreatmentStartDate` and `Received`??
- "risk group": taken from combination of `MOL1_high_risk_cohort`, `SOT02_risk_cohorts`, `CASIM05_risk_cohort`

**Comment by HelenCEBM** [comment]
@brianmackenna is going to ask about how the following fields are produced:
- Received date
- Current Status
- Count
Also: 
- Can any light be shed on how multiple form submissions occur for the same patients, either for the same drug twice or two different (outpatient) drugs?

**Comment by rebkwok** [comment]
I am almost done with implementing the study def query as defined above.  I'm not excluding or attempting to fix any duplicates or "bad" dates - for now I'll leave that to the researcher to exclude by setting a sensible date range to filter on

**Comment by acagreen17** [comment]
@rebkwok can I just check how this action will work for patients with multiple data entries...I can see how using `return_first_match_in_period = True` would work for patients with entries which have different dates, but what is the logic for patients who have say every entry the same except the drug? Is the data ordered in a particular way to make sure the same "row" is extracted every-time? 

It's been suggested that patients with duplicates should be excluded for now - how easy would it be to add something like `multiple_entries` with True/False options or what might be even better was if we could get this to work within given periods of time with options being the time frame, in say days. Implementing the latter would allow us to filter out individuals who are difficult to determine the reason behind the duplication (i.e. two drugs on the same day = impossible to tell which one they actually had) but keep in people who receive treatment say two months apart (which is more plausible). 

@HelenCEBM any thoughts?

**Comment by HelenCEBM** [comment]
I was thinking that if we have "number of matches in period" then we can filter out anyone who has 2 or more? Or query for both drugs separately and filter out anyone who has both. I'm not sure we should filter data in the backend as it would be a different approach to what we have done with every other dataset afaik, and it's useful to be able to count everyone who has a record. However, if patients have duplicates which are identical for all the fields we are using to build this query, it could be useful to collapse them into one row (not sure how easy that is though)

**Comment by rebkwok** [comment]
We can certainly remove fully duplicate rows; I'm not sure if there are any of those.  `number_of_matches_in_period` is a valid return type.
Duplicates per patient are ordered as Helen suggested - TreatmentStartDate (with direction determined by the value of `return_first_match_in_period`), Received, Intervention

**Comment by acagreen17** [comment]
Including `number_of_matches_in_period` sounds like a good idea as does removing fully duplicated rows (if there are any).

Will the default order for non TreatmentStartDate, Received, Intervention fields be alphabetical? i.e, say a patient has duplicate entries due to two regions having been entered, would "London" be extracted over "North East"?

**Comment by rebkwok** [comment]
@acagreen17 From my tests, it looks like regions would be ordered in ascending alphabetical order, but we couldn't guarantee that unless we add region to the ordering

**Comment by HelenCEBM** [comment]
Looking at the following fields (all the ones we're using to build the query I think), patients can have multiple different records for any of them, and there are a small number of patients with no differences in these fields:
![image](https://user-images.githubusercontent.com/24392156/152135333-094d2003-b56b-402d-8fc6-ecf1fa872b04.png)

We probably need to add all of these other fields into the sort order too... And it's always a limitation of cohortextractor that if someone has more than one matching record for some query on the same day we can only return the details of one of them.

**Comment by rebkwok** [comment]
The initial PR is now merged.  It implements the `with_covid_therapeutics` function as described above.
Returning options are:
- "binary_flag", 
- "date" (TreatmentStartDate), 
- "therapeutic" (Intervention), 
- "risk group"
- "region"
- "number_of_matches_in_period"

Therapeutic return type returns one comma-separated string (removing " and "s)
Risk group joins the 3 risk groups into one comma-separated string (removing " and "s and "Patient with a ").  It does NOT currently remove any duplicates, so you could end up with "cancer,cancer" as the the risk group string.  The SQL to also remove the duplicates would be really complex, and doesn't seem worth it right now.  At the moment I don't think there are any rows that would give you duplicates like this. 

Filtering by therapeutic and status are case insensitive.

Fully duplicate rows are removed and won't be counted if you use `number_of_matches_in_period`.  Other duplicate rows are kept in, and will return the first/last by treatment start date (depending on the value of `return_first_match_in_period`/`return_last_match_in_period`).  Duplicate rows per patient that have the same treatment start date will be ordered (in ascending order) by the following fields (in this order): Received, CurrentStatus, Intervention, Region, MOL1_high_risk_cohort, SOT02_risk_cohorts, CASIM05_risk_cohort

**Comment by amirmehrkar** [comment]
[Population Health COVID-19 Treatments Business Rules Simple Additions cohorts v0.1.docx](https://github.com/opensafely-core/cohort-extractor/files/8645309/Population.Health.COVID-19.Treatments.Business.Rules.Simple.Additions.cohorts.v0.1.docx)

The attached business rules that defined the eligible list (targeted patient list) for therapeutics (e.g. nMAbs/antivirals) were approved for implementation 27.4.2022

Im sure you have access already to the other files
[nMABS_AV_Community_RPS_v5_Feb 22.pdf](https://github.com/opensafely-core/cohort-extractor/files/8645315/nMABS_AV_Community_RPS_v5_Feb.22.pdf)
[Clinical Guide - Therapies for symptomatic non-hospitalised patients with COVID-19.pdf](https://github.com/opensafely-core/cohort-extractor/files/8645316/Clinical.Guide.-.Therapies.for.symptomatic.non-hospitalised.patients.with.COVID-19.pdf)

**Comment by amirmehrkar** [comment]
From NHSD @acagreen17 @brianmackenna 


_There have not been extensive changes to the code set or rule set since creation of digital cohorting for nMABs. Apologies I missed the PAG meeting for the simple additions, unfortunately I was away on leave. The major changes to the cohort since the initial code set, was the missed CLL code which was updated on the website. The latest additions do apply changes to the code set and rule set that will be updated on the methodology pages – these changes are currently being finalised. (https://digital.nhs.uk/coronavirus/treatments/methodology).

nMABs is a live cohort, rather than a physical list such as the shielded patient list._
