### ISSUE TITLE
APCS: support returning "total bed days" 

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/cohort-extractor#742]
### Use case
**Total bed days** can be used as a measure of healthcare usage, or total amount of time spent in hospital over a particular period with a certain diagnosis, even if it was across multiple spells.

### Current workaround
It is difficult to calculate total bed days per patient over a given period of time where they may have had multiple spells. Currently it would be required to extract a long sequence of admission and discharge dates over the entire period, calculate the difference between each pair and then sum, but may be imperfect, e.g. if someone has more admissions in the period than we have allowed for. 

### Existing options in this dataset which are implemented already
We currently offer the following somewhat similar `returning` options: 
- `number_of_matches_in_period` - number of times patient was admitted in time period specified.
- `days_in_critical_care` - number of days in critical care during spell.

### Suggested implementation
Should be much the same as `days_in_critical_care`:
Sum of `Der_Spell_LoS` [length of stay] for all included spells in period (we also have another field available, `Spell_LoS` in one of the linked APCS tables but I've confirmed they are identical). Required as a `returning` option only.
- However, `LoS` is measured in number of _nights_ not number of days so single-day admissions return 0, a two-day stay returns 1, and so on. Could have two options: `length_of_stay_nights` (using the field as it is) or `length_of_stay_days` (adding 1 to each value)

### Notes/issues
- If someone has a single-day admission and a longer stay both starting the same day, we would count the first day twice unless we account for this somehow. However this is relatively unusual.
- There are also a very small number of duplicates / other impossible overlapping spells so this would very occasionally return spurious results.

**Comment by rebkwok** [comment]
Qns:
1) Which is preferred - `length_of_stay_nights` (using the field as it is) or `length_of_stay_days` (adding 1 to each value)?
2) `patients_admitted_to_hospital` returns only the first or last admission (depending on the value of `find_first_match_in_period`).  The current returning value `days_in_critical_care` doesn't sum the days for all spells, it returns the number of days for the first/last match.  If `length_of_stay_nights` should calculate the summed nights (or days), I think it should be named so that it's clear that it's different to the other returning values that return days/duration for a single stay (we can also raise an error if either the `find_first_match_in_period` or `find_last_match_in_period` arguments are provided)

**Comment by HelenCEBM** [comment]
> Which is preferred - length_of_stay_nights (using the field as it is) or length_of_stay_days (adding 1 to each value)?

I think days is generally going to be more useful

> I think it should be named so that it's clear that it's different to the other returning values that return days/duration for a single stay (we can also raise an error if either the find_first_match_in_period or find_last_match_in_period arguments are provided)

I think the error is probably a good idea and we could name it `total_bed_days_in_period` or similar? Perhaps we can add the same query option for cc_days as well, i.e. `total_cc_days_in_period`?

**Comment by rebkwok** [comment]
`returning` can now include `total_bed_days_in_period` and `total_critical_care_days_in_period`.  `total_bed_days_in_period` adds 1 to `Der_Spell_LoS` return days from the length of stay recorded in nights.  If a patient has 2 spells with the same admission date, it will include only the longest stay.  

I haven't accounted for the rare duplicates or impossible overlaps that don't have identical admission dates.
