### ISSUE TITLE
Debug UOM performance issues

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/cohort-extractor#768]
[BRIT Antibiotic Research](https://jobs.opensafely.org/datalab/brit-antibiotic-research/) is a project made up of a number of repos.

* `hosp_pred` started showing problems on March 25th. It runs a number of cohort extractions, most of which ran OK, but [one of which failed](https://jobs.opensafely.org/datalab/brit-antibiotic-research/hosp_pred/6257/hilhe52wsrf7wdlq/), consistently
* Dave looked at it. One of the errors was loss of the database connection while trying to download results. The others ("Internal Error" messages) were caused by something else[^1] and re-running (after resetting status manually) worked
* On 29 March the [same error occurred](https://jobs.opensafely.org/datalab/brit-antibiotic-research/hosp_pred/6402/thdai4ntokyzgwfo/). Louis noted that other jobs, including an [LSHTM one](https://jobs.opensafely.org/lshtm/covid-19-collateral/covid-collateral/6414/6irsma3bimdnvdxs/) and [another BRIT one](https://jobs.opensafely.org/datalab/brit-antibiotic-research/service_eval_work/6411/oukmxyxa4vlnygrj/), failed at the same time - but this time with `Error Code 1`

To summarise:
* Recently, docker containers have been spinning, due to a lack of resources (presumably CPU / RAM / swapping); this triggered some special condition handling that wasn't actually needed, and had a cascade effect on other resources
* We don't think that's happening today, because we're seeing an `error 1`, which is _usually_ a failing database connection

Actions:
* [x] Check what the current errors actually are
* [x] Assuming they are database connection problems:
  * [ ] consider checking our retry logic to use exponential backoff; this will give us an opportunity to fix the connection issues without causing the jobs to fail
  * [x] Identify any underlying causes of database connection problems; consider handling them with a special case so we can monitor them better
* [x] Review the UOM studies. Why do they keep hitting these problems? Are there any unusual patterns in what they're trying to do? 
   * [ ]  If they're reusing measures, are they using the hack where each month is computed separately, to work around the fact the many-months cohortextraction is atomic?
   * [x] Are their study definitions unusual? I note they've created a codelist that's almost every single DM+D code. Do they need to do this? And will that cause performance problems? 
* [x] Review historic resource trends over the past few months. Cross-reference with failures in logs. Identify patterns that may help isolate underlying study definition patterns that could be triggering error cascades

[^1]: The "something else" mentioned above is related to a number of resource-depletion issues we've been seeing lately. Specifically, a number of docker containers were being incorrectly marked as "failed" (with an "internal error") because they were not responding to a probe that has a 5 minute timeout. In fact, these containers _were_ still running, and many of them completed; Dave manually updated their states accordingly.  This caused a knock-on effect because the special failure handling skips cleaning up old files, so disk space was gobbled up. We run the probe to handle containers that fail due to a Docker-in-Windows bug: when copying into a container, if the container is killed half-way through, the container enters some kind of deadlock - so if they don't respond after 5 minutes, we handle them with a state transition that omits our usual "file cleanup" handling

**Comment by Jongmassey** [comment]
[brit_cc_v3](https://jobs.opensafely.org/datalab/brit-antibiotic-research/brit_cc_v3/logs/) is a case-control study which has also been problematic. @alexwalkerepi and I took a look at the failing `extract_variables_outcome_1_control_*` tasks which run an extract for a reasonably wide set of variables ([1](https://github.com/opensafely/amr-uom-brit/blob/CC_AB_V3/analysis/variables_antibiotics.py) [2](https://github.com/opensafely/amr-uom-brit/blob/CC_AB_V3/analysis/variables_confounding.py) [3](https://github.com/opensafely/amr-uom-brit/blob/CC_AB_V3/analysis/variables_CCI.py) ) each for a pre-extracted monthly control patient list.

**Comment by sebbacon** [comment]
Looking into the specific error that was reported:

* 2022-03-29T16:22:35: `Running: Query for has_follow_up_previous_year`
* 2022-03-29T16:22:49: `Writing results into temporary table `OPENCoronaTempTables..DataExtract_2d3....`
* 2022-03-29T16:28:50: `MSSQLDatabaseException: (20017, b'DB-Lib error message 20017, severity 9:\nUnexpected EOF from the server\n`

One other identical error happened at the same time, for job `oukmxyxa4vlngrj`; two other identical errors have happened in March, for `hilhe52wsrf7wdlq`  (2022-03-25) and `xylsxnf3d16o3frc` (2022-03-11).

So in itself, this remains a rare event.

**Comment by sebbacon** [comment]
In terms of exotically expensive queries, [this job](https://jobs.opensafely.org/datalab/brit-antibiotic-research/brit_cc_v3/6162/m3cvw4cazmbquchu/) calls [this study definition](https://github.com/opensafely/amr-uom-brit/blob/CC_AB_V3/analysis/study_definition_outcome_1_control_2003.py) via [this action](https://github.com/opensafely/amr-uom-brit/blob/667da44ec2fb7fc620852b1d292b8e3fab415766/project.yaml#L907-L912).

This generates 566Kb of SQL which [when formatted](https://gist.github.com/bafbd61d8cc44c783bcc766ce93eca35) covers 21345 lines of code, and joins 246 tables.

I'll also note there are three codelists in the project with more than 1000 codes, which is pretty large.

**Comment by sebbacon** [comment]
In terms of other things that were going on at the same time as the database error:

* there was a [logistic model](https://jobs.opensafely.org/lshtm/vaccine-coverage-and-effectiveness-in-chronic-kidney-disease-patients/ckd-coverage-ve/6413/kez4mcqmnsrpzrw6/) that run for 2 hours and ended at 1730 with a exit code of 1 because it tried to write to `output/model/mod_strat_logistic_redacted.rds` and failed with `No such file or directory`

**Comment by Jongmassey** [comment]
>[here's how the code has changed since then](https://github.com/opensafely/amr-uom-brit/compare/c2d74b5..CC_AB_V3)

From speaking to Ya-Ting, those changes were to try and split the study def into three to reduce the large number of variables: CCI, AB, and confounding variables.

**Comment by sebbacon** [comment]
Looking at time trends over the past few months, we can see the characteristics of jobs (total number, and resources used) has not shown any particular trend:

![image](https://user-images.githubusercontent.com/211271/161058057-917e85b2-c0f8-40f9-9f25-1be57ebf788f.png)
![image](https://user-images.githubusercontent.com/211271/161057964-04fbe35d-c2f2-4f22-bc4a-316ee30fdb72.png)
![image](https://user-images.githubusercontent.com/211271/161058195-d9c81f06-053c-4ffc-b190-72fc1f9bdb19.png)


However, there is a clear trend in the characteristics of "volume" jobs (which exist to copy files in and out of workspaces)
![image](https://user-images.githubusercontent.com/211271/161058418-bc6a1937-5b11-4c04-83ea-9385ac9b8c75.png)
 
These volume jobs don't carry large memory or CPU burdens, but we do know they are IO bottlenecks (they're very slow).

Therefore, it seems likely there is an increase in workspaces that generate large numbers of files.

**Comment by bloodearnest** [comment]
These graphs do not seem at all right to me.

Firstly, there's no way we've had 50000 concurrent job containers ever. We are limited to 16 by MAX_WORKERS (recently reduced to 10).

Also there's no way we have 450TB  (4.5 x 1e14) of RAM used at any point!

There's also no way we've got 225000 volume containers.

Additionally, there's a misunderstanding about volume containers. They don't actually do the copying, job-runner does. They last the entire lifetime of the job, so their presence does not indicate copying is happening. And they are purposefully not deleted if a job errors with an internal error, so they can be left running for weeks until we manually clean them up after investigating.

**Comment by sebbacon** [comment]
> Additionally, there's a misunderstanding about volume containers. They don't actually do the copying, job-runner does.

But they _are_ a proxy for IO, right?

**Comment by bloodearnest** [comment]
> > But they are a proxy for IO, right?
> 
> They are not. They just exist as a thing we can use for interacting with volumes and exist throughout the lifecycle of each job. The fact that one is running tells you nothing about what IO is happening.

Right, that's what I was trying to say.


> > These graphs do not seem at all right to me.
> 
> I just assumed something had gone wrong with the axis labels and the interesting thing was the trend (or lack of that) in the overall shape.

Right, but the numbers seemed so wild that it made me question the shape.

Seb has confirmed these are totals per day, which explains some of the numbers.

Still not sure how we got to 225000 containers in single day, though.

**Comment by sebbacon** [comment]
It's 225000 containers if you sum across all the 5-minute samples!

**Comment by evansd** [comment]
Are they cumulative totals? i.e. they're not counts of distinct containers

**Comment by sebbacon** [comment]
So yes, the shapes are right. I've edited the previous charts, though, with some more interpretable versions of the same thing.

Any thoughts now?

I still don't follow what the volumes _are_ a proxy for. Interested given the clear trend.

**Comment by evansd** [comment]
In this case, they're effectively a proxy for the number of internal errors. When we hit those things don't get cleaned up and so the volumes and associated containers accumulate. The big drop off at the end is me clearing it all up!

**Comment by evansd** [comment]
That's certainly my reading of those charts.

**Comment by sebbacon** [comment]
* `generate_study_population_hospitalisation_1` [failed](https://jobs.opensafely.org/datalab/brit-antibiotic-research/hosp_pred_urti_2019/6554/a76pwwj3n5wtstuj/) at 2022-04-03T21:32:00 with `Unexpected EOF from the server`
* `generate_study_population_hospitalisation_2` passed in about 17 hours
* `generate_study_population_hospitalisation_3` [failed](https://jobs.opensafely.org/datalab/brit-antibiotic-research/hosp_pred_urti_2019/6554/3hyz35zzhotwkmo2/) at 2022-04-03T20:28:45 with `Unexpected EOF from the server`
* `generate_study_population_hospitalisation_4` passed in 19 hours

**Comment by sebbacon** [comment]
In summary, the project is using an unusually large number of variables, and repeating them in an unusually large number of cohort generations.  It also has a complex pipeline structure which is amenable to bugs.

We have no smoking gun to suggest system performance has in general degraded, except we do think it's possible that these cohort generations are triggering database disconnection errors which do affect all running cohortextractor jobs when they happen.  We have deployed some new retry logic which should mitigate the effect of this.

In addition we've noted the project could do with individual python scripts being broken down into smaller components, and that it appears not be being tested locally. We should encourage / help the user to run and test their code locally, as they appear to be debugging by running in the live environment.
