### ISSUE TITLE
Use exit codes to indicate specific error conditions

### ISSUE THREAD

**Issue by evansd** [opensafely-core/cohort-extractor#776]
Related to this job-runner issue:
 * https://github.com/opensafely-core/job-runner/issues/184#issuecomment-1090213792

We should add another except block here:
https://github.com/opensafely-core/cohort-extractor/blob/acf8508e25a39493a7a7beae861e57f2c4db7a43/cohortextractor/cohortextractor.py#L684-L686

This should catch all exceptions from the database (exactly what class or classes this involves is an open question) and:
 * print the trackback in the normal way by calling [`traceback.print_exc()`](https://docs.python.org/3/library/traceback.html#traceback.print_exc);
 * inspect the contents of the exception to determine the appropriate error code;
 * call `sys.exit()` with that code.

The three cases we want to distinguish at the moment are:
 * `Unexpected EOF from the server` — [example job](https://jobs.opensafely.org/datalab/brit-antibiotic-research/hosp_pred/6402/thdai4ntokyzgwfo/)
 * "Missing CodedEvent_SNOMED table" (I don't have the exact text for this, will need digging out the job log) — [example job](https://jobs.opensafely.org/university-of-leeds/cancer-surgery-service-evaluation/all_cause_mortality_with_stratification/6577/x5tvqrb4lpuiapam/)
 * Any other sort of database error

We'll need to choose exit codes for this which don't clash with anything we might be likely to generate otherwise. See:
https://tldp.org/LDP/abs/html/exitcodes.html
https://www.freebsd.org/cgi/man.cgi?query=sysexits&apropos=0&sektion=0&manpath=FreeBSD+4.3-RELEASE&format=html

**Comment by sebbacon** [comment]
We also mentioned some other errors in https://github.com/opensafely-core/job-runner/issues/184:

* `nbconvert.preprocessors.execute.DeadKernelError: Kernel died`
* `DeadKernelError("Kernel died")`
* `_tds.DatabsaeError: DBPROCESS is dead or not enabled`

Any reason you skipped those, @evansd ?
