### ISSUE TITLE
Take ownership of database notebooks

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/cohort-extractor#831]
See [this Slack thread](https://bennettoxford.slack.com/archives/C31D62X5X/p1655116006095659?thread_ts=1655109115.349399&cid=C31D62X5X) and [this one](https://bennettoxford.slack.com/archives/C63UXGB8E/p1656585042707649?thread_ts=1656521265.170339&cid=C63UXGB8E).

**Comment by iaindillingham** [comment]
opensafely-core/sqlrunner#20 and opensafely-core/sqlrunner#21 capture the work that relates to the database notebooks, which is the target of the first Slack thread; opensafely-core/sqlrunner#22 captures the work that relates to the vaccine names notebook, which is the target of the second Slack thread.
