### ISSUE TITLE
Add functions to return first/last day of school year

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/cohort-extractor#836]
**Add `first_day_of_school_year` and `last_day_of_school_year` functions.** School years in England go from 1 September to 31 August. 

The functions would be very similar to the `first_day_of_NHS_financial_year` and `last_day_of_NHS_financial_year` functions (31 March / 1 April), added with [this commit](https://github.com/opensafely-core/cohort-extractor/commit/e4f010e35b763946457b7038341f0eb9d4532230)

This is useful for most studies involving children. It also allows us to match age bands used in the COVID infection survey.

**Comment by iaindillingham** [comment]
There's some more context in [this Slack thread](https://bennettoxford.slack.com/archives/C03FB777L1M/p1656920885480899).

> Note that without this function we'd need a footnote explaining that we had to use calendar years instead of school years.
