### ISSUE TITLE
Allow OpenPROMPT test data to be queried

### ISSUE THREAD

**Issue by benbc** [opensafely-core/cohort-extractor#842]
See [this document](https://docs.google.com/document/d/1Iddm4_XuxhEhw7d9aezoG4TlWVD-grzq6s5aSeXyFvw) for context.

We are waiting for details of what the schema and query patterns for this data will be and how test data specifically will be made available.

**Comment by inglesp** [comment]
Closing, as we're trying this in ehrQL.
