### ISSUE TITLE
Pathologically slow dataset

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/cohort-extractor#993]
These db jobs take longer than a week to run, thus are caught in a potentially never ending cycle of restarts due to db maintenance mode.

Can we help the user make it faster/split it up to reduce execution time?

Job request: https://jobs.opensafely.org/the-impact-of-covid-19-on-pregnancy-treatment-pathways-and-outcomes/main_pregnancy_tx_pathways/20673/

Actions: generate_{12,8,6}wk_cohort_updated, starting here:
https://github.com/opensafely/uom_pregnancy_tx_pathways/blob/4f77fa852f1627ef8c7c7ac3f932957633192a44/project.yaml#L62

Study definition:
https://github.com/opensafely/uom_pregnancy_tx_pathways/blob/4f77fa852f1627ef8c7c7ac3f932957633192a44/analysis/study_definition_updated.py

**Comment by inglesp** [comment]
The study definition is including ethnicity in monthly extracts, which is known to be slow.  The users are going to fix this by extracting ethnicity once, and then will try again.  (See [Slack](https://bennettoxford.slack.com/archives/C02HJTL065A/p1698236917250289).)
